scan_timeout = 60
add_newline = false
[line_break]
disabled = true

[directory]
style = "bold blue"

[username]
style_user = "purple bold"
style_root = "red bold"
format = "[ $user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[ ](#F07178 bold) [$hostname](yellow bold) "
disabled = false

[cmd_duration]
format = '[$duration ](#093487 bold)'

[status]
disabled = false
format = "[$symbol $status]($style) "
not_found_symbol = "\uf010"
not_executable_symbol = "\uf46e"
sigint_symbol = "\ufb66"
map_symbol = true

[git_branch]
format = "[$symbol$branch]($style) "

[package]
format = "[$symbol$version]($style) "
symbol = "\uf8d6 "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = "\ue606 "

[nodejs]
format = "[$symbol($version )]($style)"

[php]
format = "[$symbol($version )]($style)"
symbol = "\ue608 "

[java]
format = "[${symbol}(${version} )]($style)"
symbol = "\ue256 "

[rust]
format = "[$symbol($version )]($style)"

[golang]
format = "[$symbol($version )]($style)"
symbol = "\ue626 "
